services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=nocomment
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=${DB_PW}
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=nocomment
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=nocomment
    ports:
      - '5432:5432'
